[project]
name = "pydantic-ai-mcp-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "logfire[httpx]>=3.12.0",
    "pydantic-ai[logfire]>=0.0.53",
]
